version: "3.8"
services:
  backend:
    image: node:20
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: myapp_db
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm start"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3308:3308"
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    
  adminer:
    image: adminer:latest
    ports: 
      - "8080:8080" 
    depends_on:
      - db
    
volumes:
  mysql_data:
